definitions:
  controller.CommonError:
    properties:
      error:
        type: string
    type: object
  controller.CommonResponse:
    properties:
      message:
        type: string
    type: object
  controller.CreateUserRequest:
    properties:
      age:
        type: integer
      email:
        type: string
      user_name:
        type: string
    type: object
  controller.SignIpRequest:
    properties:
      employee_name:
        type: string
      password:
        type: string
    type: object
  controller.SignUpRequest:
    properties:
      employee_name:
        type: string
      full_name:
        type: string
      password:
        type: string
    type: object
  controller.TokenPairResponse:
    properties:
      access_token_ttl_minutes:
        type: string
      refresh_token_ttl_days:
        type: string
    type: object
  models.User:
    properties:
      age:
        type: integer
      email:
        type: string
      id:
        type: integer
      user_name:
        type: string
    type: object
info:
  contact:
    email: help@socialetwork.com
    name: SocialNetwork API Service
    url: https://socialnetwork.com
  title: SocialNetwork API
paths:
  /api/users:
    get:
      description: Get list of all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.CommonError'
      summary: Get all users
      tags:
      - Users
    post:
      description: Create new user and add to database
      parameters:
      - description: new user data
        in: body
        name: request_body
        required: true
        schema:
          $ref: '#/definitions/controller.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controller.CommonResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.CommonError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/controller.CommonError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.CommonError'
      summary: Create user
      tags:
      - Users
  /api/users/{id}:
    delete:
      description: Delete user's data by ID
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.CommonResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.CommonError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.CommonError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.CommonError'
      summary: Delete user by ID
      tags:
      - Users
    get:
      description: Get user's data by ID
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.CommonError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.CommonError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.CommonError'
      summary: Get user by ID
      tags:
      - Users
    put:
      description: Update user's data by ID
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      - description: updated user data
        in: body
        name: request_body
        required: true
        schema:
          $ref: '#/definitions/controller.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.CommonResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.CommonError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.CommonError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/controller.CommonError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.CommonError'
      summary: Update user by ID
      tags:
      - Users
  /auth/refresh:
    get:
      description: Refresh token pairs
      parameters:
      - description: input refresh token
        in: header
        name: X-Refresh_token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.TokenPairResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.CommonError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.CommonError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.CommonError'
      summary: Refresh token pairs
      tags:
      - Auth
  /auth/sign-in:
    post:
      description: Enter as an employee
      parameters:
      - description: login and password
        in: body
        name: request_body
        required: true
        schema:
          $ref: '#/definitions/controller.SignIpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.TokenPairResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.CommonError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.CommonError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.CommonError'
      summary: Enter
      tags:
      - Auth
  /auth/sign-up:
    post:
      description: Create new employee and add to database
      parameters:
      - description: new employee data
        in: body
        name: request_body
        required: true
        schema:
          $ref: '#/definitions/controller.SignUpRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controller.CommonResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.CommonError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.CommonError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.CommonError'
      summary: Create employee
      tags:
      - Auth
  /ping:
    get:
      description: Check of the service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Health-check
      tags:
      - Ping
swagger: "2.0"
